export type TemplateLayout = 'classic' | 'banner' | 'sidebar' | 'minimal' | 'bold';

export interface TemplateStyle {
  id: string;
  name: string;
  tagline: string;
  category: 'Popular' | 'Corporate' | 'Creative' | 'Simple' | 'Industry';
  layout: TemplateLayout;
  /** Primary accent used for headings, table header, totals. */
  accent: string;
  /** Secondary accent for gradients / highlights. */
  accent2: string;
  /** Header text color when placed on the accent background. */
  onAccent: string;
  /** Whether the document uses a dark paper background. */
  dark: boolean;
  fontClass: 'font-sans' | 'font-display';
  /** Corner radius style of the paper. */
  rounded: boolean;
}

export const templates: TemplateStyle[] = [
  {
    id: 'modern',
    name: 'Modern',
    tagline: 'Clean gradient header with bold totals — our most popular design.',
    category: 'Popular',
    layout: 'banner',
    accent: '#4f46e5',
    accent2: '#7c3aed',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'corporate',
    name: 'Corporate',
    tagline: 'Structured, formal layout ideal for enterprises and B2B deals.',
    category: 'Corporate',
    layout: 'classic',
    accent: '#0f172a',
    accent2: '#334155',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    tagline: 'Just the essentials. Elegant whitespace and refined typography.',
    category: 'Simple',
    layout: 'minimal',
    accent: '#111827',
    accent2: '#6b7280',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'blue',
    name: 'Blue Ocean',
    tagline: 'Trustworthy blue palette that works for every professional service.',
    category: 'Popular',
    layout: 'banner',
    accent: '#0284c7',
    accent2: '#0ea5e9',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'dark',
    name: 'Midnight',
    tagline: 'Premium dark document that makes your brand stand out.',
    category: 'Creative',
    layout: 'bold',
    accent: '#6366f1',
    accent2: '#22d3ee',
    onAccent: '#ffffff',
    dark: true,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'construction',
    name: 'Construction',
    tagline: 'High-contrast amber accents built for contractors and builders.',
    category: 'Industry',
    layout: 'sidebar',
    accent: '#b45309',
    accent2: '#f59e0b',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'interior',
    name: 'Interior Design',
    tagline: 'Warm, editorial layout for designers and studios.',
    category: 'Industry',
    layout: 'sidebar',
    accent: '#9f1239',
    accent2: '#e11d48',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    tagline: 'Friendly and approachable — perfect for solo professionals.',
    category: 'Creative',
    layout: 'banner',
    accent: '#059669',
    accent2: '#10b981',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'it-company',
    name: 'IT Company',
    tagline: 'Techy gradient design for software and IT service providers.',
    category: 'Corporate',
    layout: 'banner',
    accent: '#4338ca',
    accent2: '#06b6d4',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'agency',
    name: 'Agency',
    tagline: 'Bold, confident branding for marketing and creative agencies.',
    category: 'Creative',
    layout: 'bold',
    accent: '#7c3aed',
    accent2: '#db2777',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'retail',
    name: 'Retail',
    tagline: 'Vibrant and clear — great for shops and product quotations.',
    category: 'Industry',
    layout: 'classic',
    accent: '#c2410c',
    accent2: '#ea580c',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'wholesale',
    name: 'Wholesale',
    tagline: 'Dense, data-first layout for bulk orders and distributors.',
    category: 'Industry',
    layout: 'classic',
    accent: '#166534',
    accent2: '#16a34a',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    tagline: 'Balanced, timeless design suitable for any consultancy.',
    category: 'Corporate',
    layout: 'classic',
    accent: '#1e3a8a',
    accent2: '#2563eb',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    tagline: 'Serif headings and gold accents for a luxury impression.',
    category: 'Creative',
    layout: 'minimal',
    accent: '#854d0e',
    accent2: '#ca8a04',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'invoice',
    name: 'Invoice Style',
    tagline: 'Familiar tax-invoice format with a detailed GST summary.',
    category: 'Simple',
    layout: 'classic',
    accent: '#0f766e',
    accent2: '#14b8a6',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
];

export function getTemplate(id: string): TemplateStyle {
  return templates.find((t) => t.id === id) ?? templates[0];
}
