export type TemplateLayout = 'classic' | 'banner' | 'sidebar' | 'minimal' | 'bold';

export interface TemplateStyle {
  id: string;
  name: string;
  tagline: string;
  category: 'Popular' | 'Corporate' | 'Creative' | 'Simple' | 'Industry';
  layout: TemplateLayout;
  /** Primary accent used for headings, table header, totals. */
  accent: string;
  /** Secondary accent for gradients / highlights. */
  accent2: string;
  /** Header text color when placed on the accent background. */
  onAccent: string;
  /** Whether the document uses a dark paper background. */
  dark: boolean;
  fontClass: 'font-sans' | 'font-display';
  /** Corner radius style of the paper. */
  rounded: boolean;
  /**
   * Premium templates are rendered by their own bespoke component
   * (see components/quotation/premium) instead of the shared layout engine.
   */
  premium?: boolean;
}

export const templates: TemplateStyle[] = [
  {
    id: 'modern',
    name: 'Modern',
    tagline: 'Clean gradient header with bold totals — our most popular design.',
    category: 'Popular',
    layout: 'banner',
    accent: '#4f46e5',
    accent2: '#7c3aed',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'corporate',
    name: 'Corporate',
    tagline: 'Structured, formal layout ideal for enterprises and B2B deals.',
    category: 'Corporate',
    layout: 'classic',
    accent: '#0f172a',
    accent2: '#334155',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'minimal',
    name: 'Minimal',
    tagline: 'Just the essentials. Elegant whitespace and refined typography.',
    category: 'Simple',
    layout: 'minimal',
    accent: '#111827',
    accent2: '#6b7280',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'blue',
    name: 'Blue Ocean',
    tagline: 'Trustworthy blue palette that works for every professional service.',
    category: 'Popular',
    layout: 'banner',
    accent: '#0284c7',
    accent2: '#0ea5e9',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'dark',
    name: 'Midnight',
    tagline: 'Premium dark document that makes your brand stand out.',
    category: 'Creative',
    layout: 'bold',
    accent: '#6366f1',
    accent2: '#22d3ee',
    onAccent: '#ffffff',
    dark: true,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'construction',
    name: 'Construction',
    tagline: 'High-contrast amber accents built for contractors and builders.',
    category: 'Industry',
    layout: 'sidebar',
    accent: '#b45309',
    accent2: '#f59e0b',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'interior',
    name: 'Interior Design',
    tagline: 'Warm, editorial layout for designers and studios.',
    category: 'Industry',
    layout: 'sidebar',
    accent: '#9f1239',
    accent2: '#e11d48',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'freelancer',
    name: 'Freelancer',
    tagline: 'Friendly and approachable — perfect for solo professionals.',
    category: 'Creative',
    layout: 'banner',
    accent: '#059669',
    accent2: '#10b981',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'it-company',
    name: 'IT Company',
    tagline: 'Techy gradient design for software and IT service providers.',
    category: 'Corporate',
    layout: 'banner',
    accent: '#4338ca',
    accent2: '#06b6d4',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'agency',
    name: 'Agency',
    tagline: 'Bold, confident branding for marketing and creative agencies.',
    category: 'Creative',
    layout: 'bold',
    accent: '#7c3aed',
    accent2: '#db2777',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'retail',
    name: 'Retail',
    tagline: 'Vibrant and clear — great for shops and product quotations.',
    category: 'Industry',
    layout: 'classic',
    accent: '#c2410c',
    accent2: '#ea580c',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'wholesale',
    name: 'Wholesale',
    tagline: 'Dense, data-first layout for bulk orders and distributors.',
    category: 'Industry',
    layout: 'classic',
    accent: '#166534',
    accent2: '#16a34a',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },
  {
    id: 'professional',
    name: 'Professional',
    tagline: 'Balanced, timeless design suitable for any consultancy.',
    category: 'Corporate',
    layout: 'classic',
    accent: '#1e3a8a',
    accent2: '#2563eb',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
  },
  {
    id: 'elegant',
    name: 'Elegant',
    tagline: 'Serif headings and gold accents for a luxury impression.',
    category: 'Creative',
    layout: 'minimal',
    accent: '#854d0e',
    accent2: '#ca8a04',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
  },
  {
    id: 'invoice',
    name: 'Invoice Style',
    tagline: 'Familiar tax-invoice format with a detailed GST summary.',
    category: 'Simple',
    layout: 'classic',
    accent: '#0f766e',
    accent2: '#14b8a6',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
  },

  // ---------- PREMIUM TEMPLATES (bespoke layouts) ----------
  {
    id: 'modern-corporate',
    name: 'Modern Corporate',
    tagline: 'Bold top band, floating meta card and crisp striped tables.',
    category: 'Corporate',
    layout: 'banner',
    accent: '#1d4ed8',
    accent2: '#3b82f6',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
    premium: true,
  },
  {
    id: 'minimal-clean',
    name: 'Minimal Clean',
    tagline: 'Generous whitespace, hairline rules and refined monochrome type.',
    category: 'Simple',
    layout: 'minimal',
    accent: '#111827',
    accent2: '#4b5563',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
    premium: true,
  },
  {
    id: 'premium-business',
    name: 'Premium Business',
    tagline: 'Two-tone header, section chips and an elevated total card.',
    category: 'Corporate',
    layout: 'banner',
    accent: '#0f172a',
    accent2: '#6366f1',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
    premium: true,
  },
  {
    id: 'elegant-blue',
    name: 'Elegant Blue',
    tagline: 'Full-height gradient sidebar with a polished blue palette.',
    category: 'Popular',
    layout: 'sidebar',
    accent: '#1e40af',
    accent2: '#38bdf8',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
    premium: true,
  },
  {
    id: 'dark-professional',
    name: 'Dark Professional',
    tagline: 'Sleek dark paper with neon accents and card sections.',
    category: 'Creative',
    layout: 'bold',
    accent: '#22d3ee',
    accent2: '#818cf8',
    onAccent: '#0b1220',
    dark: true,
    fontClass: 'font-sans',
    rounded: true,
    premium: true,
  },
  {
    id: 'creative-gradient',
    name: 'Creative Gradient',
    tagline: 'Vibrant diagonal gradient header with pill tables.',
    category: 'Creative',
    layout: 'banner',
    accent: '#7c3aed',
    accent2: '#ec4899',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: true,
    premium: true,
  },
  {
    id: 'luxury-gold',
    name: 'Luxury Gold',
    tagline: 'Cream paper, gold rules and an elegant serif monogram header.',
    category: 'Creative',
    layout: 'minimal',
    accent: '#b8860b',
    accent2: '#d4af37',
    onAccent: '#1a1a1a',
    dark: false,
    fontClass: 'font-display',
    rounded: false,
    premium: true,
  },
  {
    id: 'invoice-style',
    name: 'Invoice-Style',
    tagline: 'Fully bordered tax-invoice grid with GST breakup and declaration.',
    category: 'Simple',
    layout: 'classic',
    accent: '#0f766e',
    accent2: '#0d9488',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: false,
    premium: true,
  },
  {
    id: 'startup-theme',
    name: 'Startup Theme',
    tagline: 'Friendly rounded header, icon accents and a chunky total pill.',
    category: 'Creative',
    layout: 'banner',
    accent: '#16a34a',
    accent2: '#22c55e',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-sans',
    rounded: true,
    premium: true,
  },
  {
    id: 'classic-professional',
    name: 'Classic Professional',
    tagline: 'Traditional centered letterhead with formal ruled sections.',
    category: 'Corporate',
    layout: 'classic',
    accent: '#7f1d1d',
    accent2: '#b91c1c',
    onAccent: '#ffffff',
    dark: false,
    fontClass: 'font-display',
    rounded: false,
    premium: true,
  },
];

export function getTemplate(id: string): TemplateStyle {
  return templates.find((t) => t.id === id) ?? templates[0];
}
